name: 01 Initial Docker Build
# This is basic workflow
# @author: Nagm Eldin
# @Date: 01.07.2025

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  super-lint:
    name: lint code-base work
    runs-on: ubuntu-latest
    steps:        
      - name: Checkout code
        uses: docker/login-action@v2
        
      - name: Run Super-Linter built-in feature
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.NAGMELDIN_TOKEN }} 
