name: 00 Super-Linter
# This is basic workflow
# @author: Nagm Eldin
# @Date: 01.07.2025

on: push

jobs:
  super-lint:
    name: lint code-base work
    runs-on: ubuntu-latest
    steps:        
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          USER_TOKEN: ${{ secrets.NAGMELDIN_TOKEN }} 
